### ISSUE TITLE
How to benchmark?

### ISSUE THREAD

**Issue by roastduck** [ptillet/torch-blocksparse#28]
I found that there is a `bench` argument in the API commented as "timings". I'm wondering how to use that benchmarking function and how to get the results?

Besides, what do `time_c`, `time_da` and `time_db` represent? Can I get a broke-down time analysis?

Thanks in advance.

**Comment by ptillet** [comment]
Hi!

I think these may be deprecated, I will remove them from the API.

To benchmark individual kernels, I recommend to use nvprof and look at the minimum time for the sdd_kernel, dsd_kernel or dds_kernel function. Looking at the minimum time (rather than average) is important because there is some autotuning going on

**Comment by roastduck** [comment]
I have two more questions.

- Can I assume that the compilation and auto-tuning is done when I call the operator for the first time, and the consecutive runs are free from these overhead?

- Can I invoke the operator asynchronously, which means the CPU code returns immediately while the GPU code keeps running? If so, I can measure the time using CUDA's timing functions?
